#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: {{ .Chart.Name }}-initialization
#data:
#  .env: |-
#    server_user=user_please
#    server_pass=user_pass_base64
#    server_domain=domain_please
